export const clockLayout = [
  "ITLISASAMPM",
  "APQUARTERDC",
  "TWENTYXFIVE",
  "HALFSTENFTO",
  "PASTERUNINE",
  "ONESIXTHREE",
  "FOURFIVETWO",
  "EIGHTELEVEN",
  "SEVENTWELVE",
  "TENSEOCLOCK",
];
