export const Textures = [
  { texture: "/bg/stone-1.jpg", alt: "Stone", value: "stone-1" },
  { texture: "/bg/stone-2.jpg", alt: "Stone", value: "stone-2" },
  { texture: "/bg/stone-3.jpg", alt: "Stone", value: "stone-3" },
  { texture: "/bg/stone-4.jpg", alt: "Stone", value: "stone-4" },
  { texture: "/bg/wood-1.jpg", alt: "Wood", value: "wood-1" },
  { texture: "/bg/wood-2.jpg", alt: "Wood", value: "wood-2" },
  { texture: "/bg/fabric-1.jpg", alt: "Fabric", value: "fabric-1" },
  { texture: "/bg/gold-1.jpg", alt: "Gold", value: "gold-1" },
  { texture: "/bg/leather-1.jpg", alt: "Leather", value: "leather-1" },
  { texture: "/bg/concrete-1.jpg", alt: "Concrete", value: "concrete-1" },
  { texture: "/bg/concrete-2.jpg", alt: "Concrete", value: "concrete-2" },
  { texture: "/bg/rust-1.jpg", alt: "Rust", value: "rust-1" },
  { texture: "/bg/rust-2.jpg", alt: "Rust", value: "rust-2" },
  { texture: "/bg/metal-1.jpg", alt: "Metal", value: "metal-1" },
];